version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - ganache
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command: ["--accounts", "10", "--defaultBalanceEther", "100"]