name: Blockchain CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545
        options: >-
          --entrypoint=sh
          -c "ganache-cli --accounts 10 --defaultBalanceEther 100 --deterministic"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Compile contracts
      run: bash scripts/compile_contracts.sh

    - name: Deploy contracts
      run: python migrations/deploy_contracts.py
