name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      ganache:
        image: trufflesuite/ganache-cli
        ports:
          - 8545:8545
        options: --entrypoint "sh -c 'ganache-cli --accounts 10 --defaultBalanceEther 100'"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compile contracts
      run: ./scripts/compile_contracts.sh

    - name: Deploy contracts
      run: python migrations/deploy_contracts.py